#!/usr/bin/env bash
python3 -m venv env
./env/bin/pip3 install -r requirements.txt
./env/bin/python3 -c "import nltk;nltk.download('punkt')"
./env/bin/python3 -c "import nltk;nltk.download('stopwords')"
